[programs.localnet]
gifshare = "JBg1GKP7ysjTmkHfqbRxj3Hz5LwxxeEHsw6SeVcJmka8"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/dylan/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"
